# golangci-lint configuration for NTM
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

  disable:
    - funlen      # Function length - too strict for TUI code
    - gochecknoglobals  # We use package-level vars for themes/config
    - lll         # Line length - TUI rendering often needs long lines
    - wsl         # Too strict about whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives
      - fieldalignment  # Struct field ordering optimization - too noisy

  gocyclo:
    min-complexity: 20

  gocognit:
    min-complexity: 30

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - hugeParam  # TUI models are often passed by value
      - httpNoBody  # Using nil for empty body is fine
      - evalOrder  # Panics with Go 1.25 (golangci-lint/go-critic compatibility issue)

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/Dicklesworthstone/ntm

  gosec:
    excludes:
      - G104  # Unhandled errors - too noisy
      - G304  # File path from variable - we intentionally do this

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    for-loops: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
        disabled: true  # Often needed for interface compliance
      - name: unreachable-code
      - name: redefines-builtin-id

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist: []
    http-status-code-whitelist: []

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gosec
        - goconst

    # Ignore magic numbers in test files
    - path: _test\.go
      text: "Magic number"

    # TUI code often has complex View() functions
    - path: internal/tui/
      linters:
        - gocognit
        - gocyclo

    # Palette code has complex rendering
    - path: internal/palette/
      linters:
        - gocognit
        - gocyclo

    # Allow fmt.Print in CLI commands
    - path: internal/cli/
      linters:
        - forbidigo
      text: "use of `fmt.Print"

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - govet
      severity: error
